build:
  script:
    - "cp -ru /cache/root/.android /cache/root/.gradle /cache/root/.profile /cache/root/android-sdk-linux /root/ 2>/dev/null || :"
    - mkdir -p ~/.gradle/
    - cd /builds/mycelium/mycelium-com-wallet
    - echo working on branch $CI_BUILD_REF_NAME''
    - "if [ $CI_BUILD_REF_NAME'' == 'master' ]; then gradleParam=''; else gradleParam='-PskipProguard'; fi"
    - ./gradlew build $gradleParam -Pbranch=$CI_BUILD_REF_NAME''
    - "mkdir /cache/root 2>/dev/null || :"
    - cp -ru /root/.android /root/.gradle /root/.profile /root/android-sdk-linux /cache/root
  type: build
  artifacts:
    paths:
      - /builds/mycelium/mycelium-com-wallet/mbw/build/outputs/logs/
      - /builds/mycelium/mycelium-com-wallet/mbw/build/outputs/lint-results.xml
      - /builds/mycelium/mycelium-com-wallet/mbw/build/outputs/lint-results.html
      - /builds/mycelium/mycelium-com-wallet/mbw/build/outputs/lint-results_files/
      - /builds/mycelium/mycelium-com-wallet/mbw/build/outputs/apk/mbw-btctestnet-debug-*build*.apk
      - /builds/mycelium/mycelium-com-wallet/btchip/build/outputs/
      - /builds/mycelium/mycelium-com-wallet/trezor/build/outputs/
  tags:
    - 4GB_RAM
